plone:
  image: eeacms/eea.docker.
  ports:
    - "8090:8080"
  volumes:
    - ./src:/plone/instance/src
    - cca-downloads:/data/downloads
    - cca-plone-data:/data
  entrypoint: sh -c "tail -f /dev/null"
